### ISSUE TITLE
Windows already implemented in AlexaPi

### ISSUE THREAD

**Issue by EmerickH** [jraspiprojects/AlexaPi-Windows#2]
Hello @jraspiprojects,
From now more than 1 year, Windows support is already implemented in the base AlexaPi (https://github.com/alexa-pi/AlexaPi/commit/37c62af6ea152b792f97b403b5c125bd394452a8) with a setup.bat and a start.bat and without the need of swigwin (which was used in the first Windows version:  [AlexaPi-Windows-DEPRECATED](https://github.com/alexa-pi/AlexaPi-Windows-DEPRECATED), but useless because [python run without any problem on Windows](https://www.python.org/downloads/windows/)).

There's also a [Windows GUI wrapper](https://github.com/EmerickH/AlexaPiWrapper).

Have you had any problems with the "official" version?
I'm contacting you because some users are finding your project and contacting us because they don't know how to make it work...

Thank you,
Emerick

**Comment by jraspiprojects** [comment]
oh ok bye
